language: php
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.1

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/soap-client generate config/config.yml src/Service/Container --dest-class=Service/Container/SoapContainer
  - php bin/demo.php
