soap_client:
  #  alternative_endpoints:
  #    service:
  #      port: http://localhost:8080
  namespaces:
    # v1 services:
    'http://schemas.microsoft.com/2003/10/Serialization/':    'ToezichtS2S\Serialization'
    'http://rechtspraak.nl/Service/Algemeen/v1':              'ToezichtS2S\Service\Algemeen\v1'
    'http://rechtspraak.nl/Model/Algemeen/v1':                'ToezichtS2S\Model\Algemeen\v1'
    'http://rechtspraak.nl/Service/DataTypes':                'ToezichtS2S\Service\DataTypes'
    'http://rechtspraak.nl/Service/Metadata/v1':              'ToezichtS2S\Service\Metadata\v1'
    'http://rechtspraak.nl/Service/Metadata':                 'ToezichtS2S\Service\Metadata\Generic'
    'http://rechtspraak.nl/MetadataService/v1':               'ToezichtS2S\MetadataService\v1'
    'http://rechtspraak.nl/NotificatieService/v1':            'ToezichtS2S\NotificatieService\v1'
    'http://rechtspraak.nl/Service/Notificaties/v1':          'ToezichtS2S\Service\Notificaties\v1'
    'http://rechtspraak.nl/EindgebruikerService/v1':          'ToezichtS2S\EindgebruikerService\v1'
    'http://rechtspraak.nl/Service/Eindgebruikers/v1':         'ToezichtS2S\Service\Eindgebruikers\v1'

    # v2 services:
    'http://rechtspraak.nl/ToezichtS2S/Algemeen/v2':          'ToezichtS2S\Algemeen\v2'
    'http://rechtspraak.nl/ToezichtS2S/Bericht/v2':           'ToezichtS2S\Bericht\v2'
    'http://rechtspraak.nl/ToezichtS2S/Formulier/v2':         'ToezichtS2S\Formulier\v2'

  destinations_php:
    'ToezichtS2S\Model\Algemeen\v1':                          src/ToezichtS2S/Model/Algemeen/v1
    'ToezichtS2S\Serialization':                              src/ToezichtS2S/Serialization
    'ToezichtS2S\Service\Algemeen\v1':                        src/ToezichtS2S/Service/Algemeen/v1
    'ToezichtS2S\Service\DataTypes':                          src/ToezichtS2S/Service/DataTypes
    'ToezichtS2S\Service\Metadata\Generic':                   src/ToezichtS2S/Service/Metadata/Generic
    'ToezichtS2S\Service\Metadata\v1':                        src/ToezichtS2S/Service/Metadata/v1
    'ToezichtS2S\MetadataService\v1':                         src/ToezichtS2S/MetadataService/v1
    'ToezichtS2S\NotificatieService\v1':                      src/ToezichtS2S/NotificatieService/v1
    'ToezichtS2S\Service\Notificaties\v1':                    src/ToezichtS2S/Service/Notificaties/v1
    'ToezichtS2S\EindgebruikerService\v1':                    src/ToezichtS2S/EindgebruikerService/v1
    'ToezichtS2S\Service\Eindgebruikers\v1':                   src/ToezichtS2S/Service/Eindgebruikers/v1

    'ToezichtS2S\Algemeen\v2':                                src/ToezichtS2S/Algemeen/v2
    'ToezichtS2S\Bericht\v2':                                 src/ToezichtS2S/Bericht/v2
    'ToezichtS2S\Formulier\v2':                               src/ToezichtS2S/Formulier/v2

  destinations_jms:
    'ToezichtS2S\Serialization':                              metadata/Serialization
    'ToezichtS2S\Service\Algemeen\v1':                        metadata/Service/Algemeen/v1
    'ToezichtS2S\Model\Algemeen\v1':                          metadata/Model/Algemeen/v1
    'ToezichtS2S\Service\DataTypes':                          metadata/Service/DataTypes
    'ToezichtS2S\Service\Metadata\v1':                        metadata/Service/Metadata/v1
    'ToezichtS2S\Service\Metadata\Generic':                   metadata/Service/Metadata/Generic
    'ToezichtS2S\MetadataService\v1':                         metadata/MetadataService/v1
    'ToezichtS2S\NotificatieService\v1':                      metadata/NotificatieService/v1
    'ToezichtS2S\Service\Notificaties\v1':                    metadata/Service/Notificaties/v1
    'ToezichtS2S\EindgebruikerService\v1':                    metadata/EindgebruikerService/v1
    'ToezichtS2S\Service\Eindgebruikers\v1':                  metadata/Service/Eindgebruikers/v1

    'ToezichtS2S\Algemeen\v2':                                metadata/Algemeen/v2
    'ToezichtS2S\Bericht\v2':                                 metadata/Bericht/v2
    'ToezichtS2S\Formulier\v2':                               metadata/Formulier/v2

  metadata:
#    'https://api.a-rechtspraak.nl/mijnrechtspraak-test/v1/soap12mtom/metadata?singleWsdl': ~
#    './config/wsdl/bericht.v1.xml': ~
    './config/wsdl/bericht.v2.xml': ~
    './config/wsdl/eindgebruiker.v1.xml': ~
    './config/wsdl/metadata.v1.xml': ~
    './config/wsdl/notificatie.v1.xml': ~

